jobs:
   build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: action/checkout@v3
   - name: login docker
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_TOKEN}}
    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  edfather/myfirstrepository:latest