name: Chat4

on:
  push:  
env:
  IMAGE_NAME: mychatconteyner
jobs:
  Docker_Build: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: push Docker Conteiner github
       run:  docker build . -t $IMAGE_NAME -f Dockerfile
     - name: push docker conteiner ghcr.io
       run: IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:${{ github.run_id }} 
            docker push $IMAGE_ID
