name: ssh_docker
on:
  push:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: edfather
jobs:
  ssh_test:
   name: ssh_test
   runs-on: ubuntu-latest
   steps:
     - name: executing remote ssh commands 
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
     - name: login docker
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN}}
     - name: build and push
       uses: docker/build-push-action@v2
       with:
        context: .
        push: true
        tags:  edfather/myfirstrepository:latest