name: ssh_docker
on: 
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:  edfather/myfirstrepository:latest
  ssh_test:
    name: ssh_test
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: executing remote ssh commands 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: 
          - name: docker stop 
            run: docker stop $(docker ps -a ) 
          - name: docker rm
            run: docker rm $(docker ps -a -q) 
  docker_rmi_push_run:  
    name: docker_rmi_push_run
    runs-on: ubuntu-latest
    needs: ssh_test
    steps:
      - name: executing remote ssh  
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: 
            docker rmi $(docker images -a -q) |
            docker pull edfather/myfirstrepository |
            docker run --detach --publish 3000:3000  edfather/myfirstrepository:latest 
