name: ssh_docker
on:
  push:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  ssh_test:
   name: ssh_test
   runs-on: ubuntu-latest
   steps:
    - name: executing remote ssh commands 
      uses: appleboy/ssh-action@master
      with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         script: 
             docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
